/* =============================================================
   ✦  EDIT YOUR WEDDING DETAILS & GUEST LIST HERE  ✦
   -------------------------------------------------------------
   This is the ONLY file you need to change.
   No coding required — just edit the text between the quotes.

   1. Set the couple name, date, and a short welcome line.
   2. Add one line per guest or group inside the guests [ ... ] list:
          { name: "First Last", table: "Table 7" },
      - "name"  : how the guest will search for themselves
      - "table" : whatever you want shown (e.g. "Table 7", "Family Table")
   3. Keep each line ending with a comma.
   4. Save the file and refresh the page. That's it!

   (The guest list below was imported from GuestList.csv.)
   ============================================================= */

window.WEDDING = {
  // --- Event details (shown at the top of the page) ---
  couple: "Mr. Arjun and Mrs. Priyanjli\nSharma",
  date: "06.26.2026",
  welcome: "Welcome! Find your name below to discover your table.",

  // --- Guest list (order does not matter — it sorts automatically) ---
  guests: [
    { name: "Aayush Bahendwar", table: "Table 1" },
    { name: "Adi's Friends (2)", table: "Table 1" },
    { name: "Ajay & Vandana Sharma", table: "Table 17" },
    { name: "Ajeeth Sran & Family", table: "Table 8" },
    { name: "Albert Chan", table: "Table 3" },
    { name: "Amar Chabara", table: "Table 9" },
    { name: "Anderson Ng (+1)", table: "Table 3" },
    { name: "Anish Patel", table: "Table 3" },
    { name: "Ankush Bali", table: "Table 1" },
    { name: "Anupam and Navdeep Agnihotri", table: "Table 15" },
    { name: "Anuraj & Manjot Rathord", table: "Table 14" },
    { name: "Anureet Bhatti", table: "Table 34" },
    { name: "Arti Kalia Family", table: "Family Table" },
    { name: "Arun and Neeru Prabhkar", table: "Table 25" },
    { name: "Arvinder & Jessi Saini", table: "Table 18" },
    { name: "Ashleen Raina", table: "Table 34" },
    { name: "Ashwani & Pina Mehta", table: "Table 19" },
    { name: "Ashwani & Vandana Ratti Family", table: "Table 5" },
    { name: "Atul & Seema Anand", table: "Table 17" },
    { name: "Balkaran Dhillon and Dave Pandher", table: "Table 11" },
    { name: "Balwinder Sharma", table: "Table 6" },
    { name: "Bavleen Deo", table: "Table 34" },
    { name: "Bharat Verma", table: "Table 14" },
    { name: "Dat Ly", table: "Table 3" },
    { name: "David Trinh", table: "Table 3" },
    { name: "Deepa Kalra/Tushar", table: "Table 18" },
    { name: "Deepak & Sneh Gandhi", table: "Table 19" },
    { name: "Dr. Erin Zahavi", table: "Table 36" },
    { name: "Dr. Gurpreet & Satinder Malhotra +2", table: "Table 20" },
    { name: "Dr. Jaryd Te", table: "Table 36" },
    { name: "Dr. Navah Ball", table: "Table 36" },
    { name: "Dr. Pallavi Dutta", table: "Table 36" },
    { name: "Dr. Ranmeet Dulai", table: "Table 36" },
    { name: "Dr. Richard Cheng", table: "Table 36" },
    { name: "Dr. Sachin Batra", table: "Table 27" },
    { name: "Dr. Sarina Prasad", table: "Table 36" },
    { name: "Dr. Supriya Khatri", table: "Table 36" },
    { name: "Erik Kredatus", table: "Table 1" },
    { name: "Eva Ly", table: "Table 35" },
    { name: "Gagandeep/Harpreet Papneja (Bharti Office)", table: "Table 26" },
    { name: "Geeta/Gourav", table: "Table 22" },
    { name: "Gobind Singh Ghunia Family", table: "Table 4" },
    { name: "Gordy/Vick and Bobby Khuman", table: "Table 13" },
    { name: "Gourav & Manu Bhanot", table: "Table 13" },
    { name: "Gurpreet Jagdev", table: "Table 8" },
    { name: "Harman Kaul", table: "Table 1" },
    { name: "Harmeet Syal", table: "Table 26" },
    { name: "Harneet Brar", table: "Table 34" },
    { name: "Herman Kailey (+1)", table: "Table 2" },
    { name: "Jaya/Karan", table: "Table 22" },
    { name: "Jerry Huang", table: "Table 3" },
    { name: "Jonny Owusu", table: "Table 3" },
    { name: "Jyoti Kalia", table: "Table 21" },
    { name: "Kailash Manoj Sumati Sharma Family", table: "Table 5" },
    { name: "Kajan", table: "Table 35" },
    { name: "Kanta & Surdarshan Daulat", table: "Table 6" },
    { name: "Kanwaljit Aman Channe", table: "Table 7" },
    { name: "Karan Kundra", table: "Table 1" },
    { name: "Ken & Usha Sehgal +2", table: "Table 18" },
    { name: "KP (Kamalpal Singh) and Deep", table: "Table 12" },
    { name: "Kuldeep & Neena Sethi", table: "Table 20" },
    { name: "Kulwinder Deol and Family", table: "Table 11" },
    { name: "Lucky (Gurpreet) and Sumandeep Malhi", table: "Table 10" },
    { name: "Mala", table: "Table 22" },
    { name: "Manish Shah", table: "Table 11" },
    { name: "Manjit Cheema", table: "Table 9" },
    { name: "Manohar Gill", table: "Table 35" },
    { name: "Menu Aunti", table: "Table 27" },
    { name: "Mohinder Pal/Seema Chopra & Family", table: "Table 10" },
    { name: "Mohit & Isha Raghwan", table: "Table 14" },
    { name: "Morning Star Crew", table: "Table 32" },
    { name: "Mr & Mrs Sonu Gandhi", table: "Table 13" },
    { name: "Mr & Mrs. Prabjot Kaur", table: "Table 13" },
    { name: "Mr Dipin and Aditi Bhandari", table: "Table 16" },
    { name: "Mr. & Mrs. Ritesh Sharma", table: "Table 12" },
    { name: "Mr. Anil Chopra", table: "Table 33" },
    { name: "Mr. Arun Paul", table: "Table 28" },
    { name: "Mr. Baljinder Rakhra", table: "Table 28" },
    { name: "Mr. Chaman Lal Singla", table: "Table 30" },
    { name: "Mr. Denesh Kumar", table: "Table 36" },
    { name: "Mr. Dhiraj Mehta", table: "Table 27" },
    { name: "Mr. Gurjit", table: "Table 29" },
    { name: "Mr. Gurmeet Singh Saroey", table: "Table 31" },
    { name: "Mr. Jatinder Singh", table: "Table 29" },
    { name: "Mr. Kanwaljit Atwal", table: "Table 31" },
    { name: "Mr. Pushpinder Sandhu", table: "Table 29" },
    { name: "Mr. Ram Gupta", table: "Table 30" },
    { name: "Mr. S.D Sharma", table: "Table 27" },
    { name: "Mr. Subash Joshi", table: "Table 27" },
    { name: "Mr. Sukhdev Dhillion", table: "Table 31" },
    { name: "Mr. Sukhi Paul", table: "Table 28" },
    { name: "Mr. Suresh Khurana", table: "Table 33" },
    { name: "Mrs and Mr Anil Gulati", table: "Table 8" },
    { name: "Mrs and Mr Anubhav Seghal (Bharti Office)2", table: "Table 26" },
    { name: "Mrs and Mr Paul Kumar", table: "Table 9" },
    { name: "Mrs and Mr Peter Bhandari", table: "Table 9" },
    { name: "Mrs and Mr. Naresh Bhattal", table: "Table 7" },
    { name: "Ms. Ruchika Bajaj", table: "Table 33" },
    { name: "Ms. Shweta Jain", table: "Table 31" },
    { name: "Mukesh & Sunita Babbar", table: "Table 20" },
    { name: "Naresh Sharma", table: "Table 8" },
    { name: "Naval and Malti Misar", table: "Table 25" },
    { name: "Nina Bhabi", table: "Family Table" },
    { name: "Nirosha Logaratnam", table: "Table 35" },
    { name: "Nisha Logaratnam", table: "Table 35" },
    { name: "Nithusa Logaratnam", table: "Table 35" },
    { name: "Nivisha Logaratnam", table: "Table 35" },
    { name: "NS Puri", table: "Table 14" },
    { name: "Pardeep and Sangeeta Kalia", table: "Table 19" },
    { name: "Parkash & Shalini Sharma", table: "Table 17" },
    { name: "Paul and Simran Gill", table: "Table 7" },
    { name: "Paul/Puja and Family (Bharti Office)", table: "Table 26" },
    { name: "Pawan & Jyoti Sharma", table: "Table 19" },
    { name: "Poonam & Gagan Hundal", table: "Table 12" },
    { name: "Poonam & Vinod Sharma", table: "Table 14" },
    { name: "Prasoon & Anu Srivastava", table: "Table 20" },
    { name: "Prince Minhas (+1)", table: "Table 2" },
    { name: "Puja/Vick Kalia", table: "Table 22" },
    { name: "Rakesh Sharma & Jass Surry", table: "Table 16" },
    { name: "Rani/Vinod Kutwal", table: "Table 25" },
    { name: "Reena/Shashi Aunti", table: "Table 15" },
    { name: "Renu & Manoj Sehgal", table: "Table 16" },
    { name: "Ria Bharti", table: "Table 7" },
    { name: "Robert Pham", table: "Table 3" },
    { name: "Roshni Bhatti", table: "Table 34" },
    { name: "Safery Hossain (+1)", table: "Table 2" },
    { name: "Sai Oduri", table: "Table 1" },
    { name: "Sakib Khan (+1)", table: "Table 2" },
    { name: "Samaya & Anupam Dua", table: "Table 16" },
    { name: "Sameer and Monica Glascow", table: "Table 23" },
    { name: "Sana (Sandeep) Lehal", table: "Table 7" },
    { name: "Sanjeeb and Ritu Selli London (UK)", table: "Table 23" },
    { name: "Sanjeev & Ritu Nagi", table: "Table 19" },
    { name: "Sashi and Ashok Sharma", table: "Table 15" },
    { name: "Seema/Rajneesh Sharma & Ramnesh3", table: "Table 24" },
    { name: "Shallu/Ashu Family", table: "Table 4" },
    { name: "Sharan Bhuttan", table: "Table 6" },
    { name: "Shaveta Bhardwaj", table: "Table 16" },
    { name: "Shekhar & Veena Chauhan +2", table: "Table 20" },
    { name: "Siddharthdeep Sharma (Sandeep Cousin)5", table: "Table 27" },
    { name: "Sodiq Ade", table: "Table 1" },
    { name: "Sonia/David Fled", table: "Table 21" },
    { name: "Subrina and Sahil Verma", table: "Table 23" },
    { name: "Sudesh & Kiran Kalia", table: "Family Table" },
    { name: "Sukhdev Sahota", table: "Table 6" },
    { name: "Sumeet Dhillion", table: "Table 34" },
    { name: "Sumit/Shivani Selli (Sandeep Cousin)", table: "Table 24" },
    { name: "Sunakshi & Vikrant Saini", table: "Table 12" },
    { name: "Surjeevan Atwal", table: "Table 35" },
    { name: "Tamana & Raj Mago", table: "Table 6" },
    { name: "Tamanna Atwal", table: "Table 34" },
    { name: "Triasha/Vinnie", table: "Table 21" },
    { name: "Usha Didi and Family London (UK)", table: "Table 24" },
    { name: "Vanessa Ye", table: "Table 3" },
    { name: "Vhaishy Murugathas", table: "Table 35" },
    { name: "Vic Dogra", table: "Table 13" },
    { name: "Vijay & Ashok Sharma", table: "Table 17" },
    { name: "Vijay Mamma/Kavita Sharma", table: "Table 25" },
    { name: "Vijay/Bhashi", table: "Table 25" },
    { name: "Vikas/Bibek Abhi & Family", table: "Table 9" },
    { name: "Vinay", table: "Table 27" },
    { name: "Vishal & Suba Kalia Family", table: "Family Table" },
    { name: "Yadwinder/Jyoti Bawa and Family", table: "Table 18" },
    { name: "Youvraj", table: "Table 27" },
  ],
};
