/* =============================================================
   ✦  EDIT YOUR WEDDING DETAILS & GUEST LIST HERE  ✦
   -------------------------------------------------------------
   This is the ONLY file you need to change.
   No coding required — just edit the text between the quotes.

   1. Set the couple name, date, and a short welcome line.
   2. Add one line per guest or group inside the guests [ ... ] list:
          { name: "First Last", table: "Table 7" },
      - "name"  : how the guest will search for themselves
      - "table" : whatever you want shown (e.g. "Table 7", "Family Table")
   3. Keep each line ending with a comma.
   4. Save the file and refresh the page. That's it!

   (The guest list below was imported from GuestList.csv.)
   ============================================================= */

window.WEDDING = {
  // --- Event details (shown at the top of the page) ---
  couple: "Olivia & James",
  date: "Saturday, the 12th of September",
  welcome: "Welcome! Find your name below to discover your table.",

  // --- Guest list (order does not matter — it sorts automatically) ---
  guests: [
    { name: "Aayush Bahendwar", table: "Table 1" },
    { name: "Adi's Friends (2)", table: "Table 1" },
    { name: "Ajay & Vandana Sharma (KITTY GROUP)-4", table: "Table 17" },
    { name: "Ajeeth Sran (REMAX)-4", table: "Table 8" },
    { name: "Albert Chan", table: "Table 3" },
    { name: "Amar Chabara (REMAX)-2", table: "Table 9" },
    { name: "Anderson Ng (+1)", table: "Table 3" },
    { name: "Anish Patel", table: "Table 3" },
    { name: "Ankush Bali", table: "Table 1" },
    { name: "ANUPAM AND NAVDEEP AGNIHOTRI-2", table: "Table 15" },
    { name: "Anuraj & Manjot Rathord-2", table: "Table 14" },
    { name: "Arti kalia (Family)-3", table: "Family Table" },
    { name: "Arun and Neeru Prabhkar (Family)-2", table: "Table 25" },
    { name: "Arvinder & Jessi Saini(Kitty Group)-4", table: "Table 18" },
    { name: "Ashwani & Pina Mehta (kitty group)-2", table: "Table 19" },
    { name: "Ashwani/vandana Ratti Family)-5", table: "Table 5" },
    { name: "Atul & Seema Anand (KITTY GROUP)-2", table: "Table 17" },
    { name: "Balkaran Dhillon and Dave Pandher(Bharti Office)-5", table: "Table 11" },
    { name: "Balwinder Sharma (REMAX)-2", table: "Table 6" },
    { name: "bharat verma-2", table: "Table 14" },
    { name: "Dat Ly", table: "Table 3" },
    { name: "David Trinh", table: "Table 3" },
    { name: "Deepa Kalra/Tushar (Kitty Group)-2", table: "Table 18" },
    { name: "Deepak & Sneh Gandhi Kitty Group)-2", table: "Table 19" },
    { name: "Dr.Gurpreet & Satinder Malhotra(KITTY GROUP)+2", table: "Table 20" },
    { name: "Erik Kredatus", table: "Table 1" },
    { name: "Gagandeep /Harpreet Papneja (Bharti Office)-4", table: "Table 26" },
    { name: "Geeta/Gourav (Family)-4", table: "Table 22" },
    { name: "Gobind singh Ghunia ( Family)-7", table: "Table 4" },
    { name: "Gordy,vICK AND BOBBY Khuman REMAX)-3", table: "Table 13" },
    { name: "Gourav & Manu Bhanot (REMAX) -2", table: "Table 13" },
    { name: "GURPREET JAGDEV (REMAX)-2", table: "Table 8" },
    { name: "Harman Kaul", table: "Table 1" },
    { name: "Harmeet Syal-1", table: "Table 26" },
    { name: "Herman Kailey (+1)", table: "Table 2" },
    { name: "Jaya /Karan family)-2", table: "Table 22" },
    { name: "Jerry Huang", table: "Table 3" },
    { name: "Jonny Owusu", table: "Table 3" },
    { name: "Jyoti kalia (Family)-1", table: "Table 21" },
    { name: "K P(Kamalpal singh) and Deep-2", table: "Table 12" },
    { name: "Kailash,Manoj,Sumati Sharma (family)-5", table: "Table 5" },
    { name: "Kanta & Surdarshan Daulat (REMAX)-2", table: "Table 6" },
    { name: "KANWALJIT AMAN CHANNE (REMAX)-2", table: "Table 7" },
    { name: "Karan Kundra", table: "Table 1" },
    { name: "Ken & Usha Sehgal( kitty Group)+2", table: "Table 18" },
    { name: "Kuldeep & Neena Sethi 9KITTY GROUP)-2", table: "Table 20" },
    { name: "Kulwinder Deol and Family (Bharti Office)-5", table: "Table 11" },
    { name: "Lucky(Gurpreet) and Sumandeep Malhi-4", table: "Table 10" },
    { name: "Mala (Family)-2", table: "Table 22" },
    { name: "Manish Shah( Bharti Office)-2", table: "Table 11" },
    { name: "Manjit Cheema (REMAX)-2", table: "Table 9" },
    { name: "Menu aunti - 1", table: "Table 27" },
    { name: "Mohinder Pal ,Seema Chopra & Family6", table: "Table 10" },
    { name: "Mohit & Isha Raghwan-2", table: "Table 14" },
    { name: "Mr &Mrs .Prabjot Kaur(REMAX) -2", table: "Table 13" },
    { name: "Mr &Mrs Sonu GandhI (REMAX)-2", table: "Table 13" },
    { name: "Mr Dipin and Aditi Bhandari-2", table: "Table 16" },
    { name: "Mr. & Mrs. Ritesh Sharma ( Family)-3", table: "Table 12" },
    { name: "Mrs and Mr Anil Gulati (REMAX)-2", table: "Table 8" },
    { name: "Mrs and Mr Anubhav Seghal (BHARTI OFFICE)2", table: "Table 26" },
    { name: "MRS AND MR PAUL KUMAR (REMAX) - 2", table: "Table 9" },
    { name: "Mrs and Mr Peter Bhandari(Remax)-2", table: "Table 9" },
    { name: "Mrs and Mr. Naresh Bhattal (REMAX)-2", table: "Table 7" },
    { name: "Mukesh & Sunita Babbar (KITTY GROUP)-4", table: "Table 20" },
    { name: "NARESH SHARMA (REMAX)-2", table: "Table 8" },
    { name: "Naval and Malti Misar (Family)-2", table: "Table 25" },
    { name: "Nina Bhabi", table: "Family Table" },
    { name: "NS Puri-2", table: "Table 14" },
    { name: "Pardeep and Sangeeta Kalia(Kitty Group)-2", table: "Table 19" },
    { name: "Parkash & Shalini Sharma (KITTY GROUP0-2", table: "Table 17" },
    { name: "Paul /Puja and Family (Bharti Office)-5", table: "Table 26" },
    { name: "PAUL and SIMRAN GILL (REMAX)-2", table: "Table 7" },
    { name: "Pawan & Jyoti Sharma (KITTY GROUP)-3", table: "Table 19" },
    { name: "Poonam & Gagan Hundal-2", table: "Table 12" },
    { name: "Poonam & Vinod Sharma-2", table: "Table 14" },
    { name: "Prasoon & Anu Srivastava (KITTY GROUP)-2", table: "Table 20" },
    { name: "Prince Minhas (+1)", table: "Table 2" },
    { name: "Puja /Vick Kalia ( Family)-2", table: "Table 22" },
    { name: "Rakesh Sharma & Jass Surry (family)-1", table: "Table 16" },
    { name: "Rani/Vinod kutwal (Family)-2", table: "Table 25" },
    { name: "Reena /shashi aunti-3", table: "Table 15" },
    { name: "Renu & Manoj Sehgal-2", table: "Table 16" },
    { name: "Ria Bharti (REMAX)-2", table: "Table 7" },
    { name: "Robert Pham", table: "Table 3" },
    { name: "Safery Hossain (+1)", table: "Table 2" },
    { name: "Sai Oduri", table: "Table 1" },
    { name: "Sakib Khan (+1)", table: "Table 2" },
    { name: "Samaya & Anupam Dua-2", table: "Table 16" },
    { name: "Sameer and Monica Glascow (family)-2", table: "Table 23" },
    { name: "Sana (sandeep)Lehal REMAX)-2", table: "Table 7" },
    { name: "sandeep -5", table: "Family Table" },
    { name: "Sanjeeb and Ritu Selli London (UK)(family)-6", table: "Table 23" },
    { name: "Sanjeev & Ritu Nagi (Kitty Group)-2", table: "Table 19" },
    { name: "Sashi and ASHOK sharma-5", table: "Table 15" },
    { name: "Seema /Rajneesh Sharma & Ramnesh (Family)3", table: "Table 24" },
    { name: "Shallu/Ashu (family)-3", table: "Table 4" },
    { name: "Sharan Bhuttan (REMAX)-2", table: "Table 6" },
    { name: "SHAVETA BHARDWAJ (REMAX) -1", table: "Table 16" },
    { name: "Shekhar & Veena Chauhan (kITTY GROUP)+2", table: "Table 20" },
    { name: "SIddharthdeep Sharma ( sandeep Cousin)5", table: "Table 27" },
    { name: "Sodiq Ade", table: "Table 1" },
    { name: "Sonia /David Fled (Family)-5", table: "Table 21" },
    { name: "Subrina And Sahil Verma (Family)-2", table: "Table 23" },
    { name: "sudesh kalia-2", table: "Family Table" },
    { name: "Sukhdev Sahota (REMAX)-2", table: "Table 6" },
    { name: "Sumit,Shivani Selli(SANDEEP COUSIN)-2", table: "Table 24" },
    { name: "Sunakshi & Vikrant saini (Family)-2", table: "Table 12" },
    { name: "Tamana & Raj Mago (REMAX)-2", table: "Table 6" },
    { name: "Triasha /vinnie (Family)-4", table: "Table 21" },
    { name: "Usha didi and Family London (UK)(family)-7", table: "Table 24" },
    { name: "Vanessa Ye", table: "Table 3" },
    { name: "Vic Dogra (REMAX)-1", table: "Table 13" },
    { name: "vijay & ashok SHARMA(KITTY GROUP)-2", table: "Table 17" },
    { name: "Vijay Mamma /kavita sharma (Family)-2", table: "Table 25" },
    { name: "Vijay/Bhashi (family)-2", table: "Table 25" },
    { name: "Vikas,Bibek Abhi (Remax)-4", table: "Table 9" },
    { name: "vinay-1", table: "Table 27" },
    { name: "vishal /suba kalia (Family)-5", table: "Family Table" },
    { name: "Yadwinder ,Jyoti Bawa and Family(Kitty Group)-4", table: "Table 18" },
    { name: "Youvraj-1", table: "Table 27" },
  ],
};
