/* =============================================================
   ✦  EDIT YOUR WEDDING DETAILS & GUEST LIST HERE  ✦
   -------------------------------------------------------------
   This is the ONLY file you need to change.
   No coding required — just edit the text between the quotes.

   1. Set the couple name, date, and a short welcome line.
   2. Add one line per guest or group inside the guests [ ... ] list:
          { name: "First Last", table: "Table 7" },
      - "name"  : how the guest will search for themselves
      - "table" : whatever you want shown (e.g. "Table 7", "Family Table")
   3. Keep each line ending with a comma.
   4. Save the file and refresh the page. That's it!

   (The guest list below was imported from GuestList.csv.)
   ============================================================= */

window.WEDDING = {
  // --- Event details (shown at the top of the page) ---
  couple: "Mr. Arjun & Mrs. Priyanjli\nSharma",
  date: "06.26.2026",
  welcome: "Welcome! Find your name below to discover your table.",

  // --- Guest list (order does not matter — it sorts automatically) ---
  guests: [
    { name: "Aayush Bahendwar", table: "Table 21" },
    { name: "Ajay & Vandana Sharma (4)", table: "Table 18" },
    { name: "Ajeeth Sran & Family (4)", table: "Table 36" },
    { name: "Albert Chan", table: "Table 19" },
    { name: "Amar Chabara (2)", table: "Table 26" },
    { name: "Anderson Ng (2)", table: "Table 19" },
    { name: "Anil Chopra", table: "Table 32" },
    { name: "Anil Gulati (2)", table: "Table 36" },
    { name: "Anish Patel", table: "Table 19" },
    { name: "Ankush Bali", table: "Table 21" },
    { name: "Anubhav Seghal (2)", table: "Table 7" },
    { name: "Anupam & Navdeep Agnihotri", table: "Table 3" },
    { name: "Anuraj & Manjot Rathord", table: "Table 23" },
    { name: "Anureet Bhatti", table: "Table 13" },
    { name: "Arti Kalia Family", table: "Family Table" },
    { name: "Arun & Neeru Prabhkar", table: "Table 4" },
    { name: "Arun Paul", table: "Table 30" },
    { name: "Arvinder & Jessi Saini (4)", table: "Table 17" },
    { name: "Ashleen Raina", table: "Table 13" },
    { name: "Ashwani & Pina Mehta", table: "Table 15" },
    { name: "Ashwani & Vandana Ratti Family (5)", table: "Table 12" },
    { name: "Atul & Seema Anand", table: "Table 18" },
    { name: "Baljinder Rakhra", table: "Table 30" },
    { name: "Balkaran Dhillon & Dave Pandher (5)", table: "Table 8" },
    { name: "Balwinder Sharma (2)", table: "Table 34" },
    { name: "Bavleen Deo", table: "Table 13" },
    { name: "Bharat & Sumiti Verma", table: "Table 23" },
    { name: "Bobby Khuman", table: "Table 25" },
    { name: "Chaman Lal Singla", table: "Table 28" },
    { name: "Dat Ly", table: "Table 19" },
    { name: "David Trinh", table: "Table 19" },
    { name: "Deepa Kalra & Tushar", table: "Table 17" },
    { name: "Deepak & Sneh Gandhi", table: "Table 15" },
    { name: "Denesh Kumar", table: "Table 14" },
    { name: "Dhiraj Mehta", table: "Table 29" },
    { name: "Dipin & Aditi Bhandari", table: "Table 24" },
    { name: "Erik Kredatus", table: "Table 22" },
    { name: "Erin Zahavi", table: "Table 14" },
    { name: "Eva Ly", table: "Table 20" },
    { name: "Gagandeep & Harpreet Papneja (4)", table: "Table 7" },
    { name: "Geeta & Gourav", table: "Table 9" },
    { name: "Gobind Singh Ghunia Family (7)", table: "Table 2" },
    { name: "Gordy Khuman", table: "Table 25" },
    { name: "Gourav & Manu Bhanot", table: "Table 25" },
    { name: "Gurjit", table: "Table 31" },
    { name: "Gurmeet Singh Saroey", table: "Table 27" },
    { name: "Gurpreet & Satinder Malhotra", table: "Table 16" },
    { name: "Gurpreet Jagdev (2)", table: "Table 36" },
    { name: "Harman Kaul", table: "Table 21" },
    { name: "Harmeet Syal", table: "Table 7" },
    { name: "Harneet Brar", table: "Table 13" },
    { name: "Herman Kailey (2)", table: "Table 22" },
    { name: "Jaryd Te", table: "Table 14" },
    { name: "Jatinder Singh", table: "Table 31" },
    { name: "Jaya & Karan Salwan", table: "Table 9" },
    { name: "Jerry Huang", table: "Table 21" },
    { name: "Jonny Owusu", table: "Table 21" },
    { name: "Jyoti Kalia", table: "Table 6" },
    { name: "Kailash Manoj Sumati Sharma Family (5)", table: "Table 12" },
    { name: "Kajan", table: "Table 20" },
    { name: "Kanta & Surdarshan Daulat", table: "Table 34" },
    { name: "Kanwaljit Atwal", table: "Table 27" },
    { name: "Kanwaljit Channe (2)", table: "Table 35" },
    { name: "Karan Kundra", table: "Table 21" },
    { name: "Ken & Usha Sehgal", table: "Table 17" },
    { name: "KP (Kamalpal Singh) & Deep", table: "Table 5" },
    { name: "Kuldeep & Neena Sethi", table: "Table 16" },
    { name: "Kulwinder Deol & Family (5)", table: "Table 8" },
    { name: "Lucky (Gurpreet) & Sumandeep Malhi (4)", table: "Table 10" },
    { name: "Mala", table: "Table 9" },
    { name: "Manish Shah (2)", table: "Table 8" },
    { name: "Manjit Cheema (2)", table: "Table 26" },
    { name: "Manohar Gill", table: "Table 20" },
    { name: "Menu Bhalla", table: "Table 5" },
    { name: "Michael Lam", table: "Table 19" },
    { name: "Mohinder Pal/Seema Chopra & Family (6)", table: "Table 10" },
    { name: "Mohit & Isha Raghwan", table: "Table 23" },
    { name: "Morning Star Crew", table: "Table 33" },
    { name: "Mrigank Mehta", table: "Table 21" },
    { name: "Mukesh & Sunita Babbar (4)", table: "Table 16" },
    { name: "Naresh Bhattal (2)", table: "Table 35" },
    { name: "Naresh Sharma (2)", table: "Table 36" },
    { name: "Navah Ball", table: "Table 14" },
    { name: "Naval & Malti Misar", table: "Table 4" },
    { name: "Nina Selli", table: "Family Table" },
    { name: "Nirosha Logaratnam", table: "Table 20" },
    { name: "Nisha Logaratnam", table: "Table 20" },
    { name: "Nithusa Logaratnam", table: "Table 20" },
    { name: "Nivisha Logaratnam", table: "Table 20" },
    { name: "NS Puri (2)", table: "Table 23" },
    { name: "Pallavi Dutta", table: "Table 14" },
    { name: "Pardeep & Sangeeta Kalia", table: "Table 15" },
    { name: "Parkash & Shalini Sharma", table: "Table 18" },
    { name: "Paul & Puja Family (5)", table: "Table 7" },
    { name: "Paul & Simran Gill", table: "Table 35" },
    { name: "Paul Kumar (2)", table: "Table 26" },
    { name: "Pawan & Jyoti Sharma (3)", table: "Table 15" },
    { name: "Peter Bhandari (2)", table: "Table 26" },
    { name: "Poonam & Gagan Hundal", table: "Table 5" },
    { name: "Poonam & Vinod Sharma", table: "Table 23" },
    { name: "Prabjot Kaur (2)", table: "Table 25" },
    { name: "Prasoon & Anu Srivastava", table: "Table 16" },
    { name: "Prince Minhas (3)", table: "Table 22" },
    { name: "Puja & Vick Kalia", table: "Table 9" },
    { name: "Pushpinder Sandhu", table: "Table 31" },
    { name: "Rakesh Sharma", table: "Table 24" },
    { name: "Ram Gupta", table: "Table 28" },
    { name: "Rani & Vinod Kutwal", table: "Table 4" },
    { name: "Ranmeet Dulai", table: "Table 14" },
    { name: "Reena & Dev (3)", table: "Table 3" },
    { name: "Renu & Manoj Sehgal", table: "Table 24" },
    { name: "Ria Bharti (2)", table: "Table 35" },
    { name: "Richard Cheng", table: "Table 14" },
    { name: "Ritesh Sharma (3)", table: "Table 5" },
    { name: "Robert Pham", table: "Table 21" },
    { name: "Roshni Bhatti", table: "Table 13" },
    { name: "Ruchika Bajaj", table: "Table 32" },
    { name: "S.D Sharma", table: "Table 29" },
    { name: "Sachin Batra", table: "Table 29" },
    { name: "Safery Hossain (2)", table: "Table 22" },
    { name: "Sai Oduri", table: "Table 21" },
    { name: "Sakib Khan (2)", table: "Table 22" },
    { name: "Samaya & Anupam Dua", table: "Table 24" },
    { name: "Sameer & Monica", table: "Table 11" },
    { name: "Sana (Sandeep) Lehal (2)", table: "Table 35" },
    { name: "Sanjeeb & Ritu Selli (6)", table: "Table 11" },
    { name: "Sanjeev & Ritu Nagi", table: "Table 15" },
    { name: "Sarina Prasad", table: "Table 14" },
    { name: "Sashi & Ashok Sharma (5)", table: "Table 3" },
    { name: "Seema & Rajneesh Sharma (3)", table: "Table 1" },
    { name: "Shallu/Ashu Family (3)", table: "Table 2" },
    { name: "Sharan Bhuttan (2)", table: "Table 34" },
    { name: "Shaveta Bhardwaj", table: "Table 24" },
    { name: "Shekhar & Veena Chauhan", table: "Table 16" },
    { name: "Shweta Jain", table: "Table 27" },
    { name: "Siddharthdeep Sharma (5)", table: "Table 24" },
    { name: "Sodiq Ade", table: "Table 19" },
    { name: "Sonia & David Fled (5)", table: "Table 6" },
    { name: "Sonu Gandhi (2)", table: "Table 25" },
    { name: "Subash Joshi", table: "Table 29" },
    { name: "Subrina & Sahil Verma", table: "Table 11" },
    { name: "Sudesh & Kiran Kalia", table: "Family Table" },
    { name: "Sukhdev Dhillion", table: "Table 27" },
    { name: "Sukhdev Sahota (2)", table: "Table 34" },
    { name: "Sukhi Paul", table: "Table 30" },
    { name: "Sumeet Dhillion", table: "Table 13" },
    { name: "Sumit & Shivani Selli", table: "Table 1" },
    { name: "Sunakshi & Vikrant Saini", table: "Table 5" },
    { name: "Supriya Khatri", table: "Table 14" },
    { name: "Suresh Khurana", table: "Table 32" },
    { name: "Surjeevan Atwal", table: "Table 20" },
    { name: "Tamana & Raj Mago", table: "Table 34" },
    { name: "Tamanna Atwal", table: "Table 13" },
    { name: "Triasha & Vinnie (4)", table: "Table 6" },
    { name: "Usha & Family (7)", table: "Table 1" },
    { name: "Vanessa Ye", table: "Table 21" },
    { name: "Vhaishy Murugathas", table: "Table 20" },
    { name: "Vic Dogra", table: "Table 25" },
    { name: "Vick Khuman", table: "Table 25" },
    { name: "Vijay & Ashok Sharma", table: "Table 18" },
    { name: "Vijay & Bhashi", table: "Table 4" },
    { name: "Vijay & Kavita Sharma", table: "Table 4" },
    { name: "Vikas & Bibek Abhi & Family (4)", table: "Table 26" },
    { name: "Vinay", table: "Table 19" },
    { name: "Vishal & Suba Kalia Family", table: "Family Table" },
    { name: "Yadwinder & Jyoti Bawa (4)", table: "Table 17" },
    { name: "Youvraj", table: "Table 19" },
  ],
};
